Function InstallChocoPackages {
	# https://github.com/mwrock/boxstarter/issues/241#issuecomment-336028348
	New-Item -Path "C:\Temp" -ItemType Directory -Force | Out-Null

	choco feature enable -n=allowGlobalConfirmation

	choco install jre8 --yes --cache-location="E:\Boxstarter\Temp" --package-parameters="/exclude:32"
	choco install everything --yes --cache-location="E:\Boxstarter\Temp" --install-arguments="'/service /run-on-system-startup /efu-association'"
	choco install git --yes --cache-location="E:\Boxstarter\Temp"
	choco install directx --yes --cache-location="E:\Boxstarter\Temp"
	choco install microsoft-edge --yes --cache-location="E:\Boxstarter\Temp"
	choco install vcredist2005 --yes --cache-location="E:\Boxstarter\Temp"
	choco install vcredist2008 --yes --cache-location="E:\Boxstarter\Temp"
	choco install vcredist2010 --yes --cache-location="E:\Boxstarter\Temp"
	choco install vcredist2012 --yes --cache-location="E:\Boxstarter\Temp"
	choco install vcredist2013 --yes --cache-location="E:\Boxstarter\Temp"
	choco install vcredist140 --yes --cache-location="E:\Boxstarter\Temp"
	choco install dotnetfx --yes --cache-location="E:\Boxstarter\Temp"
	choco install lockhunter --yes --cache-location="E:\Boxstarter\Temp"
	choco install vscode --yes --cache-location="E:\Boxstarter\Temp"
	choco install postman --yes --cache-location="E:\Boxstarter\Temp"
	choco install sumatrapdf --yes --cache-location="E:\Boxstarter\Temp"
	choco install notepadplusplus --yes --cache-location="E:\Boxstarter\Temp"
	choco install 7zip --yes --cache-location="E:\Boxstarter\Temp"
	choco install firefox --yes --cache-location="E:\Boxstarter\Temp"
	choco install googlechrome --yes --cache-location="E:\Boxstarter\Temp"
	choco install mpc-hc-clsid2 --yes --cache-location="E:\Boxstarter\Temp"
	choco install calibre --yes --cache-location="E:\Boxstarter\Temp"
	choco install dropbox --yes --cache-location="E:\Boxstarter\Temp"
	choco install ccleaner --yes --cache-location="E:\Boxstarter\Temp"
	choco install f.lux --yes --cache-location="E:\Boxstarter\Temp"
	choco install rainmeter --yes --cache-location="E:\Boxstarter\Temp"
	choco install malwarebytes --yes --cache-location="E:\Boxstarter\Temp"
	choco install irfanview --yes --cache-location="E:\Boxstarter\Temp"
	choco install tor-browser --yes --cache-location="E:\Boxstarter\Temp"
	choco install 1password4 --yes --cache-location="E:\Boxstarter\Temp"
	choco install discord --yes --cache-location="E:\Boxstarter\Temp"
	choco install slack --yes --cache-location="E:\Boxstarter\Temp"
	choco install microsoft-windows-terminal --yes --cache-location="E:\Boxstarter\Temp"
	choco install wget --yes --cache-location="E:\Boxstarter\Temp"
	choco install geforce-experience --yes --cache-location="E:\Boxstarter\Temp"
	choco install geforce-game-ready-driver --yes --cache-location="E:\Boxstarter\Temp"
	choco install logitechgaming --yes --cache-location="E:\Boxstarter\Temp"
	choco install wire --yes --cache-location="E:\Boxstarter\Temp"
	choco install exiftool --yes --cache-location="E:\Boxstarter\Temp"
	choco install multimc --yes --cache-location="E:\Boxstarter\Temp"
	choco install krita --yes --cache-location="E:\Boxstarter\Temp"
	choco install inkscape --yes --cache-location="E:\Boxstarter\Temp"
	choco install motorolamobiledrivers --yes --cache-location="E:\Boxstarter\Temp"
	choco install winscp --yes --cache-location="E:\Boxstarter\Temp"
	choco install sqlitebrowser --yes --cache-location="E:\Boxstarter\Temp"
	choco install visualstudio2019community --cacheLocation="E:\Boxstarter\Temp"
}

Export-ModuleMember -Function InstallChocoPackages
